apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: observability
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
