apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-pod-reader-binding
  namespace: observability
subjects:
  - kind: ServiceAccount
    name: default  # Cambia este nombre si tu ServiceAccount es diferente
    namespace: observability
roleRef:
  kind: Role
  name: prometheus-pod-reader
  apiGroup: rbac.authorization.k8s.io