apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: observability
  name: prometheus-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints", "services"]
    verbs: ["get", "list", "watch"]